### ISSUE TITLE
Can't add unix paths to logger file paths

### ISSUE THREAD

**Issue by keenanjohnson** [LabVIEW-DCAF/TDMSModule#17]
I want to run the TDMS logger locally on my CRIO, however, the Datalogger Configuration screen converts any path to a windows path, so I can't run it on the real time system.

**Comment by smithed** [comment]
I can't recall exactly but I think it will convert the paths automatically when you deploy.

**Comment by Beazurt** [comment]
Yeah that is how it should work. You enter the unix path, it looks like a windows path in the editor on windows, but then gets converted back to unix on the target. Let us know if that isn't how it is actually working. This is definitely still a usability issue even if its working as expected.

**Comment by keenanjohnson** [comment]
Interesting. Does it strip off the drive information and replace it with the root slash?

This behavior is pretty counter intuitive and should probably be documented somewhere.

**Comment by smithed** [comment]
I believe it uses the path to strings (https://zone.ni.com/reference/en-XX/help/371361L-01/glang/path_to_array_of_strings/) function, and then uses the reverse on the target. This may have some weird behavior that is worth looking at. For our use it works because linux-rt includes a symlink for /c/ and /C/ which points to the labview user folder. If I remember correctly, we've always used this directory, and part of the reason is we can be absolutely certain that the folders will have write access. If you start at root on linux-rt, many folders will not be write accessible to the lvuser account. A better solution is possible but I don't think its been necessary so far.

**Comment by pollockm** [comment]
FYI @keenanjohnson - I'm making edits to the module to permit direct entry of Linux-style paths when targeted to a Linux device.  Initial attempt already added to the repo - feel free to try it out.
