### ISSUE TITLE
Handle Linux paths better when TDMS module used on Linux targets

### ISSUE THREAD

**Issue by pollockm** [LabVIEW-DCAF/TDMSModule#21]
Currently, we use a Windows path control to select a path.  This makes no sense for Linux-style paths.  LabVIEW R & D uses string controls for path entry on remote Linux RT targets.  Suggest we use file path control on Windows, string control on Linux.

**Comment by pollockm** [comment]
Planning to postpone conversion to path until run time.  Will store all path information as strings in configuration.

**Comment by smithed** [comment]
It might make more sense to let users select a base directory and relative path (as a string control) rather than trying to have the user (effectively) hard-code the value. I'd suggest this: http://zone.ni.com/reference/en-XX/help/371361H-01/glang/get_system_directory/
That way the behavior is at least consistent across targets, and you dont risk issues if you change the OS value of your target.

The only issue with this is if they wanted to use a non-C drive on windows.

**Comment by pollockm** [comment]
I'm also considering the 'log stuff to attached USB drive' case on Linux targets.  I see this as a reasonably common use case, especially for TDMS datalogging

**Comment by smithed** [comment]
Its only windows that has an issue there since linux puts everything in the same tree relative to root, which is an option for that get system directory function ("Boot Volume Root"). But yeah, I don't think there would be a problem with also allowing an absolute path as you suggested.
